export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM"
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM"
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"